name: quizapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  firebase_auth: ^6.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  internet_connection_checker: ^3.0.1
  font_awesome_flutter: ^10.12.0
  syncfusion_flutter_calendar: ^31.2.3
  syncfusion_flutter_datepicker: ^31.2.3
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  flutter_zoom_drawer: ^3.1.2
  supabase_flutter: ^2.10.3
  bloc: ^9.1.0
  get_it: ^9.0.5
  units_converter: ^3.0.4
  flutter_bloc: ^9.1.1
  app_links: ^6.3.3
  uuid: ^4.5.2
  google_sign_in: ^6.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/quizlogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/quizlogo.png
    - assets/images/logo.png
